# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2019 by Helmut Konrad Fahrendholz. All rights reserved.
# This file is property of Helmut Konrad Fahrendholz. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================

from os.path import exists
from os.path import join

from hey import ROOT

TEST_DATA = join(ROOT, 'tests/resources')

assert exists(TEST_DATA), TEST_DATA

BOXES_BOXES = 'rawmaker__boxes_boxes.yaml'
FONTS_CONTENT = 'rawmaker__fonts_content.yaml'
FONTS_HEADER = 'rawmaker__fonts_header.yaml'
HORIZONTAL = 'rawmaker__boxes_horizontal.yaml'
ONELINE_FONTS_CONTENT = 'rawmaker__oneline_fonts_content.yaml'
ONELINE_FONTS_HEADER = 'rawmaker__oneline_fonts_header.yaml'
ONELINE_POSITION = 'rawmaker__oneline_text_positions.yaml'
ONELINE_TEXT = 'rawmaker__oneline_text_text.yaml'
PAGESIZE = 'rawmaker__border_pages.yaml'
TEXT = 'rawmaker__text_text.yaml'
TEXT_POSITION = 'rawmaker__text_positions.yaml'
TOC = 'rawmaker__toc_toc.yaml'

# restruct

RESTRUCT = join(TEST_DATA, 'restruct')
RESTRUCT_BOXES = join(RESTRUCT, BOXES_BOXES)
RESTRUCT_FONT_CONTENT = join(RESTRUCT, FONTS_CONTENT)
RESTRUCT_FONT_HEADER = join(RESTRUCT, FONTS_HEADER)
RESTRUCT_HORIZONTAL = join(RESTRUCT, HORIZONTAL)
RESTRUCT_ONELINE_FONT_CONTENT = join(RESTRUCT, ONELINE_FONTS_CONTENT)
RESTRUCT_ONELINE_FONT_HEADER = join(RESTRUCT, ONELINE_FONTS_HEADER)
RESTRUCT_ONELINE_POSITION = join(RESTRUCT, ONELINE_POSITION)
RESTRUCT_ONELINE_TEXT = join(RESTRUCT, ONELINE_TEXT)
RESTRUCT_PAGESIZE = join(RESTRUCT, PAGESIZE)
RESTRUCT_PDF = join(RESTRUCT, 'restructuredtext.pdf')
RESTRUCT_TEXT = join(RESTRUCT, TEXT)
RESTRUCT_TEXT_POSITION = join(RESTRUCT, TEXT_POSITION)
RESTRUCT_TOC = join(RESTRUCT, TOC)

RESTRUCT_TOC_LINES = 13

# simple

SIMPLE = join(TEST_DATA, 'simple')
SIMPLE_FONT_CONTENT = join(SIMPLE, FONTS_CONTENT)
SIMPLE_FONT_HEADER = join(SIMPLE, FONTS_HEADER)
SIMPLE_HORIZONTAL = join(SIMPLE, HORIZONTAL)
SIMPLE_ONELINE_FONT_CONTENT = join(SIMPLE, ONELINE_FONTS_CONTENT)
SIMPLE_ONELINE_FONT_HEADER = join(SIMPLE, ONELINE_FONTS_HEADER)
SIMPLE_ONELINE_TEXT = join(SIMPLE, ONELINE_TEXT)
SIMPLE_PAGESIZE = join(SIMPLE, PAGESIZE)
SIMPLE_TEXT = join(SIMPLE, TEXT)
SIMPLE_TEXT_POSITION = join(SIMPLE, TEXT_POSITION)
SIMPLE_TOC = join(SIMPLE, TOC)

SIMPLE_HEADLINES_PAGE_3 = 4
SIMPLE_TOC_LINES = 12

# porting module

PYPORTING = join(TEST_DATA, 'porting_module')
PYPORTING_FONT_CONTENT = join(PYPORTING, FONTS_CONTENT)
PYPORTING_FONT_HEADER = join(PYPORTING, FONTS_HEADER)
PYPORTING_HORIZONTAL = join(PYPORTING, HORIZONTAL)
PYPORTING_ONELINE_FONT_CONTENT = join(PYPORTING, ONELINE_FONTS_CONTENT)
PYPORTING_ONELINE_FONT_HEADER = join(PYPORTING, ONELINE_FONTS_HEADER)
PYPORTING_ONELINE_TEXT = join(PYPORTING, ONELINE_TEXT)
PYPORTING_PAGESIZE = join(PYPORTING, PAGESIZE)
PYPORTING_TEXT = join(PYPORTING, TEXT)
PYPORTING_TEXT_POSITION = join(PYPORTING, TEXT_POSITION)
PYPORTING_TOC = join(PYPORTING, TOC)

RESOURCES = [
    PYPORTING,
    PYPORTING_FONT_CONTENT,
    PYPORTING_FONT_HEADER,
    PYPORTING_HORIZONTAL,
    PYPORTING_ONELINE_FONT_CONTENT,
    PYPORTING_ONELINE_FONT_HEADER,
    PYPORTING_ONELINE_TEXT,
    PYPORTING_PAGESIZE,
    PYPORTING_TEXT,
    PYPORTING_TEXT_POSITION,
    PYPORTING_TOC,
    RESTRUCT,
    RESTRUCT_BOXES,
    RESTRUCT_FONT_CONTENT,
    RESTRUCT_FONT_HEADER,
    RESTRUCT_HORIZONTAL,
    RESTRUCT_ONELINE_FONT_CONTENT,
    RESTRUCT_ONELINE_FONT_HEADER,
    RESTRUCT_ONELINE_POSITION,
    RESTRUCT_ONELINE_TEXT,
    RESTRUCT_PAGESIZE,
    RESTRUCT_PDF,
    RESTRUCT_TEXT,
    RESTRUCT_TEXT_POSITION,
    RESTRUCT_TOC,
    SIMPLE,
    SIMPLE_FONT_CONTENT,
    SIMPLE_FONT_HEADER,
    SIMPLE_HORIZONTAL,
    SIMPLE_ONELINE_FONT_CONTENT,
    SIMPLE_ONELINE_FONT_HEADER,
    SIMPLE_ONELINE_TEXT,
    SIMPLE_PAGESIZE,
    SIMPLE_TEXT,
    SIMPLE_TEXT_POSITION,
    SIMPLE_TOC,
]
